# Generated by Django 4.2.3 on 2023-11-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_card_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='number',
        ),
    ]
