# Generated by Django 4.2.3 on 2023-11-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_card_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
